{
  "formatVersion": "1.1",
  "component": {
    "group": "me.clip",
    "module": "VoteParty",
    "version": "2.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "VoteParty-2.34.jar",
          "url": "VoteParty-2.34.jar",
          "size": 3453061,
          "sha512": "8c916ca1fc24e3deafa07285909dc56619cace61b7bc206361ebd0426c639cda2ce748e8ca387624b7d3c55d44ea62b4474daf8da2bf4f91aa72105a9812bc7d",
          "sha256": "6ebb195578ee3008ebcf401a5383638456343cda2b0fec4a58f1af0b0c5b501a",
          "sha1": "7fdae648e8d8add07b4767a0d5eef8e567317198",
          "md5": "118dad9920837975ce38c2b38b0046ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "ch.jalu",
          "module": "configme",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "co.aikar",
          "module": "acf-paper",
          "version": {
            "requires": "0.5.1-SNAPSHOT"
          }
        },
        {
          "group": "com.github.cryptomorin",
          "module": "XSeries",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-bukkit",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "me.clip",
          "module": "version",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "me.clip",
          "module": "version_old",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "me.clip",
          "module": "version_new",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "VoteParty-2.34.jar",
          "url": "VoteParty-2.34.jar",
          "size": 3453061,
          "sha512": "8c916ca1fc24e3deafa07285909dc56619cace61b7bc206361ebd0426c639cda2ce748e8ca387624b7d3c55d44ea62b4474daf8da2bf4f91aa72105a9812bc7d",
          "sha256": "6ebb195578ee3008ebcf401a5383638456343cda2b0fec4a58f1af0b0c5b501a",
          "sha1": "7fdae648e8d8add07b4767a0d5eef8e567317198",
          "md5": "118dad9920837975ce38c2b38b0046ea"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VoteParty-2.34-all.jar",
          "url": "VoteParty-2.34-all.jar",
          "size": 3453061,
          "sha512": "8c916ca1fc24e3deafa07285909dc56619cace61b7bc206361ebd0426c639cda2ce748e8ca387624b7d3c55d44ea62b4474daf8da2bf4f91aa72105a9812bc7d",
          "sha256": "6ebb195578ee3008ebcf401a5383638456343cda2b0fec4a58f1af0b0c5b501a",
          "sha1": "7fdae648e8d8add07b4767a0d5eef8e567317198",
          "md5": "118dad9920837975ce38c2b38b0046ea"
        }
      ]
    }
  ]
}
